# gfw_create_bulk_report ------------------------------------------------------

#' Create a bulk report based on specified filters and spatial parameters
#'
#' @description
#' This is an internal function to generate a bulk report based on specified
#' filters and spatial parameters (GeoJSON or predefined regions).
#'
#' **Disclaimer:**
#' Depending on the complexity and size of your request (e.g., large geojson or region,
#' long date range etc), generating the bulk report can take several minutes to
#' several hours.
#'
#' @details
#' For detailed information about the Create a Bulk Report API endpoint, please refer to the
#' official Global Fishing Watch API documentation:
#' - https://globalfishingwatch.org/our-apis/documentation#create-a-bulk-report
#' - https://globalfishingwatch.org/our-apis/documentation#bulk-download-api
#'
#' For more details on the Create a Bulk Report data caveats, please refer to the
#' official Global Fishing Watch API documentation:
#' - https://globalfishingwatch.org/our-apis/documentation#sar-fixed-infrastructure-data-caveats
#'
#' @param name Required. Character. Human-readable name of the bulk report. Example:
#' `"sar-fixed-infrastructure-data-20240903"`.
#'
#' @param dataset Required. Character. Dataset that will be used to create the bulk report.
#' Defaults to `"public-fixed-infrastructure-data:latest"`.
#' Allowed values: `"public-fixed-infrastructure-data:latest"`.
#' Example: `"public-fixed-infrastructure-data:latest"`.
#'
#' @param geojson Optional. Character string, a nested list representing GeoJSON or an `sf`, `sfc`, `sfg` object.
#' Custom GeoJSON geometry to filter the bulk report. Defaults to `NULL`.
#' Example: `list(type = "Polygon", coordinates = [...])`.
#'
#' @param format Required. Character. Bulk report result format. Defaults to `"CSV"`.
#' Allowed values: `"JSON"`, `"CSV"`. Example: `"CSV"`.
#'
#' @param region Optional. List. Predefined region information to filter the bulk report.
#' Must contain `dataset` (one of `"public-eez-areas"`, `"public-mpa-all"`, `"public-rfmo"`)
#' and `id` (non-empty string). Defaults to `NULL`. Example: `list(dataset = "public-eez-areas", id = "8466")`.
#'
#' @param filters Optional. Character vector. Filters to apply when generating the bulk report.
#' Example: `c("label = 'oil'")`.
#'
#' @param key Character. API token. Defaults to [gfw_auth()].
#'
#' @param print_request Boolean. Whether to print the request, for debugging
#' purposes. When contacting the GFW team it will be useful to send this string.
#'
#' @return
#' A single-row tibble with the created bulk report metadata and status,
#' containing following columns:
#' \describe{
#'   \item{`id`}{Unique identifier (UUID) of the bulk report.}
#'   \item{`name`}{Human-readable name of the bulk report.}
#'   \item{`filepath`}{Name of the output file generated by the bulk report.}
#'   \item{`format`}{Format of the generated bulk report file.}
#'   \item{`filters`}{List of applied filters used when generating the bulk report.}
#'   \item{`geom`}{Geography used when generating the bulk report.}
#'   \item{`status`}{Current status of the bulk report generation process.}
#'   \item{`ownerId`}{Identifier (ID) of the entity that created the bulk report.}
#'   \item{`ownerType`}{Type of entity that created the bulk report.}
#'   \item{`createdAt`}{Timestamp when the bulk report was created in ISO-8601 format.}
#'   \item{`updatedAt`}{Timestamp when the bulk report was last updated in ISO-8601 format.}
#'   \item{`fileSize`}{Size of the bulk report output file in bytes.}
#' }
#'
#' @examples
#' \dontrun{
#' library(gfwr)
#'
#' # Create a bulk report for SAR fixed infrastructure with oil structure filters in Argentina EEZ
#' report_region <- gfw_create_bulk_report(
#'   name = "sar-vessel-detection-gfwr-package-example-1",
#'   dataset = "public-fixed-infrastructure-data:latest",
#'   format = "CSV",
#'   region = list(
#'     dataset = "public-eez-areas",
#'     id = "8466"
#'   ),
#'   filters = c(
#'     "label = 'oil'",
#'     "structure_start_date between '2020-01-01' and '2025-01-01'"
#'   ),
#'   print_request = TRUE
#' )
#'
#' # Create a bulk report for SAR fixed infrastructure with oil structure filters using custom GeoJSON
#' geojson <- list(
#'   type = "Polygon",
#'   coordinates = list(
#'     list(
#'       c(-180.0, -85.0511287798066),
#'       c(-180.0, 0.0),
#'       c(0.0, 0.0),
#'       c(0.0, -85.0511287798066),
#'       c(-180.0, -85.0511287798066)
#'     )
#'   )
#' )
#'
#' report_geojson <- gfw_create_bulk_report(
#'   name = "sar-vessel-detection-gfwr-package-example-2",
#'   dataset = "public-fixed-infrastructure-data:latest",
#'   format = "CSV",
#'   geojson = geojson,
#'   filters = c(
#'     "label = 'oil'",
#'     "structure_start_date between '2020-01-01' and '2025-01-01'"
#'   ),
#'   print_request = TRUE
#' )
#' }
#'
#' @keywords internal
#' @noRd
gfw_create_bulk_report <- function(name = NULL,
                                   dataset = "public-fixed-infrastructure-data:latest",
                                   geojson = NULL,
                                   format = "CSV",
                                   region = NULL,
                                   filters = NULL,
                                   key = gfw_auth(),
                                   print_request = FALSE) {
  ## Validate report name -----------------------------------------------------
  if (!rlang::is_string(name) || !nzchar(name)) {
    rlang::abort("`name` is required and must be a non-empty character string.")
  }

  ## Validate dataset ---------------------------------------------------------
  if (!rlang::is_string(dataset) || !nzchar(dataset)) {
    rlang::abort("`dataset` is required and must be a non-empty character string.")
  }

  dataset <- rlang::arg_match0(
    arg = trimws(as.character(dataset)),
    values = c("public-fixed-infrastructure-data:latest"),
    arg_nm = "dataset"
  )

  ## Validate format ----------------------------------------------------------
  if (!rlang::is_string(format) || !nzchar(format)) {
    rlang::abort("`format` is required and must be a non-empty character string.")
  }

  format <- rlang::arg_match0(
    arg = toupper(trimws(as.character(format))),
    values = c("JSON", "CSV"),
    arg_nm = "format"
  )

  ## Validate filters ---------------------------------------------------------
  if (!is.null(filters)) {
    if (!is.character(filters) || length(filters) == 0 || any(is.na(filters) | !nzchar(trimws(filters)))) {
      rlang::abort("`filters` must be a non-empty character vector with valid strings.")
    }
    filters <- as.list(trimws(filters))
  }

  ## Validate region ----------------------------------------------------------
  if (!is.null(region)) {
    if (!is.list(region)) {
      rlang::abort("`region` must be a list containing `dataset` and `id`.")
    }

    region_dataset <- trimws(as.character(region$dataset))
    if (!rlang::is_string(region_dataset) || !nzchar(region_dataset)) {
      rlang::abort("`region$dataset` is required and must be a non-empty character string.")
    }
    region_dataset <- rlang::arg_match0(
      arg = region_dataset,
      values = c("public-eez-areas", "public-mpa-all", "public-rfmo"),
      arg_nm = "region$dataset"
    )

    region_id <- trimws(as.character(region$id))
    if (!rlang::is_string(region_id) || !nzchar(region_id)) {
      rlang::abort("`region$id` is required and must be a non-empty character string.")
    }

    region <- list(dataset = region_dataset, id = region_id)
  }

  ## Validate geojson ---------------------------------------------------------
  if (!is.null(geojson)) {
    geojson_sf_obj <- tryCatch(
      {
        if (inherits(geojson, "sf")) {
          geojson
        } else if (inherits(geojson, "sfc")) {
          sf::st_sf(geometry = geojson)
        } else if (inherits(geojson, "sfg")) {
          sf::st_sf(geometry = sf::st_sfc(geojson, crs = 4326))
        } else if (rlang::is_string(geojson)) {
          geojsonsf::geojson_sf(geojson)
        } else if (is.list(geojson) && !rlang::is_empty(geojson) && rlang::is_named(geojson)) {
          geojson |>
            jsonlite::toJSON(auto_unbox = TRUE) |>
            geojsonsf::geojson_sf()
        } else {
          rlang::abort("`geojson` must be a sf/sfc/sfg object, character string (JSON)
          or a nested list representing GeoJSON.")
        }
      },
      error = function(e) {
        rlang::abort(
          message = "`geojson` could not be parsed into a valid spatial object.
          Ensure it is a valid sf/sfc/sfg object, character string (JSON) or a nested list representing GeoJSON.",
          parent = e
        )
      }
    )

    if (sf::st_is_empty(geojson_sf_obj) || !all(sf::st_is_valid(geojson_sf_obj))) {
      rlang::abort(
        message = "`geojson` is not a valid spatial object.
          Ensure it is a valid sf/sfc/sfg object, character string (JSON) or a nested list representing GeoJSON.",
      )
    }

    geojson <- geojson_sf_obj |>
      geojsonsf::sf_geojson(atomise = TRUE) |>
      jsonlite::fromJSON(simplifyVector = FALSE)
  }

  ## Validate key -------------------------------------------------------------
  if (!rlang::is_string(key) || !nzchar(key)) {
    rlang::abort("No API token found. Set `GFW_TOKEN` or pass `key`.")
  }

  ## Build API request body ---------------------------------------------------
  req_body <- list(
    name = name,
    dataset = dataset,
    geojson = geojson,
    format = format,
    region = region,
    filters = filters
  ) |> purrr::discard(is.null)

  ## Build API request --------------------------------------------------------
  req <- httr2::request(gfw_base_url()) |>
    httr2::req_url_path_append("bulk-reports") |>
    httr2::req_auth_bearer_token(key) |>
    httr2::req_headers(
      `Content-Type` = "application/json"
    ) |>
    httr2::req_user_agent(gfw_user_agent()) |>
    httr2::req_body_json(req_body) |>
    httr2::req_error(body = \(x) parse_response_error(x)$formatted)

  if (print_request) {
    print(req)
  }

  # Perform request
  resp <- req |> httr2::req_perform()

  ## Build API response -------------------------------------------------------

  # Extract JSON response body
  resp_body <- httr2::resp_body_json(resp, check_type = TRUE, simplifyVector = FALSE)

  # Normalize and transform response body to dataframe
  resp_df <- resp_body |>
    purrr::map(\(val) {
      if (is.null(val)) NA else if (is.list(val) || length(val) > 1) list(val) else val
    }) |>
    tibble::as_tibble_row()

  return(resp_df)
}

# gfw_get_bulk_report_by_id ---------------------------------------------------

#' Get a bulk report by ID
#'
#' @description
#' This is internal function to retrieves metadata and status of the previously
#' created bulk report based on the provided bulk report ID.
#'
#' **Important:**
#' We recommend to use this method to poll the status of previously created
#' bulk report, if it takes several minutes or hours to generate until it status
#' is `"done"` or `"failed"`.
#'
#' @details
#' For detailed information about the Get Bulk Report by ID API endpoint, please refer to the
#' official Global Fishing Watch API documentation:
#' - https://globalfishingwatch.org/our-apis/documentation#get-bulk-report-by-id
#' - https://globalfishingwatch.org/our-apis/documentation#bulk-download-api
#'
#' For more details on the Get Bulk Report by ID data caveats, please refer to the
#' official Global Fishing Watch API documentation:
#' - https://globalfishingwatch.org/our-apis/documentation#sar-fixed-infrastructure-data-caveats
#'
#' @param id Required. Character. Unique identifier (ID) of the bulk report. Example:
#' `"adbb9b62-5c08-4142-82e0-b2b575f3e058"`.
#'
#' @param key Character. API token. Defaults to [gfw_auth()].
#'
#' @param print_request Boolean. Whether to print the request, for debugging
#' purposes. When contacting the GFW team it will be useful to send this string.
#'
#' @return
#' A single-row tibble with the previously created bulk report metadata and status,
#' containing following columns:
#' \describe{
#'   \item{`id`}{Unique identifier (UUID) of the bulk report.}
#'   \item{`name`}{Human-readable name of the bulk report.}
#'   \item{`filepath`}{Name of the output file generated by the bulk report.}
#'   \item{`format`}{Format of the generated bulk report file.}
#'   \item{`filters`}{List of applied filters used when generating the bulk report.}
#'   \item{`geom`}{Geography used when generating the bulk report.}
#'   \item{`status`}{Current status of the bulk report generation process.}
#'   \item{`ownerId`}{Identifier (ID) of the entity that created the bulk report.}
#'   \item{`ownerType`}{Type of entity that created the bulk report.}
#'   \item{`createdAt`}{Timestamp when the bulk report was created in ISO-8601 format.}
#'   \item{`updatedAt`}{Timestamp when the bulk report was last updated in ISO-8601 format.}
#'   \item{`fileSize`}{Size of the bulk report output file in bytes.}
#' }
#'
#' @examples
#' \dontrun{
#' library(gfwr)
#'
#' # Retrieve most recent successfully completed report
#' completed_reports <- gfw_get_all_bulk_reports(
#'   limit = 1,
#'   sort = "-createdAt",
#'   status = "done"
#' )
#' report_id <- completed_reports$id[[1]]
#'
#' # Retrieve metadata and check status for a specific bulk report
#' report <- gfw_get_bulk_report_by_id(
#'   id = report_id,
#'   print_request = TRUE
#' )
#'
#' # Access status to determine if report is ready for download
#' if (report$status == "done") {
#'   message("Report is ready!")
#' }
#' }
#'
#' @keywords internal
#' @noRd
gfw_get_bulk_report_by_id <- function(id = NULL,
                                      key = gfw_auth(),
                                      print_request = FALSE) {
  ## Validate report id -------------------------------------------------------
  if (!rlang::is_string(id) || !nzchar(id)) {
    rlang::abort("`id` is required and must be a non-empty character string.")
  }

  ## Validate key -------------------------------------------------------------
  if (!rlang::is_string(key) || !nzchar(key)) {
    rlang::abort("No API token found. Set `GFW_TOKEN` or pass `key`.")
  }

  ## Build API request --------------------------------------------------------
  req <- httr2::request(gfw_base_url()) |>
    httr2::req_url_path_append("bulk-reports", id) |>
    httr2::req_auth_bearer_token(key) |>
    httr2::req_headers(
      `Content-Type` = "application/json"
    ) |>
    httr2::req_user_agent(gfw_user_agent()) |>
    httr2::req_error(body = \(x) parse_response_error(x)$formatted)

  if (print_request) {
    print(req)
  }

  # Perform request
  resp <- req |> httr2::req_perform()

  ## Build API response -------------------------------------------------------

  # Extract JSON response body
  resp_body <- httr2::resp_body_json(resp, check_type = TRUE, simplifyVector = FALSE)

  # Normalize and transform response body to dataframe
  resp_df <- resp_body |>
    purrr::map(\(val) {
      if (is.null(val)) NA else if (is.list(val) || length(val) > 1) list(val) else val
    }) |>
    tibble::as_tibble_row()

  return(resp_df)
}

# gfw_get_bulk_report_file_download_url ---------------------------------------

#' Get signed URL to download file of the previously created bulk report
#'
#' @description
#' This is internal function to Retrieves signed URL that points to a downloadable
#' file hosted on Global Fishing Watch's cloud infrastructure to download file(s)
#' (i.e., `"DATA"`, `"README"`, or `"GEOM"`) of the previously created bulk report.
#'
#' @details
#' For detailed information about the Download bulk Report (URL File) API endpoint,
#' please refer to the official Global Fishing Watch API documentation:
#' - https://globalfishingwatch.org/our-apis/documentation#download-bulk-report-url-file
#' - https://globalfishingwatch.org/our-apis/documentation#bulk-download-api
#'
#' For more details on the Download bulk Report (URL File) data caveats, please refer to the
#' official Global Fishing Watch API documentation:
#' - https://globalfishingwatch.org/our-apis/documentation#sar-fixed-infrastructure-data-caveats
#'
#' @param id Required. Character. Unique identifier (ID) of the bulk report. Example:
#' `"adbb9b62-5c08-4142-82e0-b2b575f3e058"`.
#'
#' @param file Required. Character. Type of bulk report file. Defaults to `"DATA"`.
#' Allowed values: `"DATA"`, `"README"`, `"GEOM"`. Example: `"DATA"`.
#'
#' @param key Character. API token. Defaults to [gfw_auth()].
#'
#' @param print_request Boolean. Whether to print the request, for debugging
#' purposes. When contacting the GFW team it will be useful to send this string.
#'
#' @return
#' A single-row tibble with the signed URL to download bulk report file,
#' containing following columns:
#' \describe{
#'   \item{`url`}{The signed URL for downloading the requested file.}
#' }
#'
#' @examples
#' \dontrun{
#' library(gfwr)
#'
#' # Retrieve most recent successfully completed report
#' completed_reports <- gfw_get_all_bulk_reports(
#'   limit = 1,
#'   sort = "-createdAt",
#'   status = "done"
#' )
#' report_id <- completed_reports$id[[1]]
#'
#' # Get signed URL for the main data file
#' data_url <- gfw_get_bulk_report_file_download_url(
#'   id = report_id,
#'   file = "DATA"
#' )
#'
#' # Get signed URL for the README documentation file
#' readme_url <- gfw_get_bulk_report_file_download_url(
#'   id = report_id,
#'   file = "README",
#'   print_request = TRUE
#' )
#' }
#'
#' @keywords internal
#' @noRd
gfw_get_bulk_report_file_download_url <- function(id = NULL,
                                                  file = NULL,
                                                  key = gfw_auth(),
                                                  print_request = FALSE) {
  ## Validate report id -------------------------------------------------------
  if (!rlang::is_string(id) || !nzchar(id)) {
    rlang::abort("`id` is required and must be a non-empty character string.")
  }

  ## Validate file ------------------------------------------------------------
  if (!rlang::is_string(file) || !nzchar(file)) {
    rlang::abort("`file` is required and must be a non-empty character string.")
  }

  file <- rlang::arg_match0(
    arg = toupper(trimws(as.character(file))),
    values = c("DATA", "README", "GEOM"),
    arg_nm = "file"
  )

  ## Validate key -------------------------------------------------------------
  if (!rlang::is_string(key) || !nzchar(key)) {
    rlang::abort("No API token found. Set `GFW_TOKEN` or pass `key`.")
  }

  ## Build API request --------------------------------------------------------
  req <- httr2::request(gfw_base_url()) |>
    httr2::req_url_path_append("bulk-reports", id, "download-file-url") |>
    httr2::req_url_query(file = file) |>
    httr2::req_auth_bearer_token(key) |>
    httr2::req_headers(
      `Content-Type` = "application/json"
    ) |>
    httr2::req_user_agent(gfw_user_agent()) |>
    httr2::req_error(body = \(x) parse_response_error(x)$formatted)

  if (print_request) {
    print(req)
  }

  # Perform request
  resp <- req |> httr2::req_perform()

  ## Build API response -------------------------------------------------------

  # Extract JSON response body
  resp_body <- httr2::resp_body_json(resp, check_type = TRUE, simplifyVector = FALSE)

  # Normalize and transform response body to dataframe
  resp_df <- resp_body |>
    purrr::map(\(val) {
      if (is.null(val)) NA else if (is.list(val) || length(val) > 1) list(val) else val
    }) |>
    tibble::as_tibble_row()

  return(resp_df)
}

# gfw_get_all_bulk_reports ----------------------------------------------------

#' Get all bulk reports created by user or application
#'
#' @description
#' This is internal function to retrieve a list of metadata and status of the
#' previously created bulk reports based on specified pagination, sorting, and
#' filtering criteria.
#'
#' @details
#' For detailed information about the Get All Bulk Reports API endpoint, please refer to the
#' official Global Fishing Watch API documentation:
#' - https://globalfishingwatch.org/our-apis/documentation#get-all-bulk-reports-by-user
#' - https://globalfishingwatch.org/our-apis/documentation#bulk-download-api
#'
#' For more details on the Get All Bulk Reports data caveats, please refer to the
#' official Global Fishing Watch API documentation:
#' - https://globalfishingwatch.org/our-apis/documentation#sar-fixed-infrastructure-data-caveats
#'
#' @param limit Optional. Integer. Maximum number of bulk reports to return.
#' Defaults to `99999`. Example: `99999`.
#'
#' @param offset Optional. Integer. Number of bulk reports to skip before returning results.
#' Defaults to `0`. Example: `0`.
#'
#' @param sort Optional. Character. Property to sort the bulk reports by.
#' Defaults to `"-createdAt"`. Example: `"-createdAt"`.
#'
#' @param status Optional. Character. Current status of the bulk report generation process.
#' Defaults to `NULL`. Allowed values: `"pending"`, `"processing"`, `"done"`, `"failed"`.
#' Example: `"done"`.
#'
#' @param key Character. API token. Defaults to [gfw_auth()].
#'
#' @param print_request Boolean. Whether to print the request, for debugging
#' purposes. When contacting the GFW team it will be useful to send this string.
#'
#' @return
#' A tibble with the previously created bulk reports metadata and status,
#' containing following columns:
#' \describe{
#'   \item{`id`}{Unique identifier (UUID) of the bulk report.}
#'   \item{`name`}{Human-readable name of the bulk report.}
#'   \item{`filepath`}{Name of the output file generated by the bulk report.}
#'   \item{`format`}{Format of the generated bulk report file.}
#'   \item{`filters`}{List of applied filters used when generating the bulk report.}
#'   \item{`geom`}{Geography used when generating the bulk report.}
#'   \item{`status`}{Current status of the bulk report generation process.}
#'   \item{`ownerId`}{Identifier (ID) of the entity that created the bulk report.}
#'   \item{`ownerType`}{Type of entity that created the bulk report.}
#'   \item{`createdAt`}{Timestamp when the bulk report was created in ISO-8601 format.}
#'   \item{`updatedAt`}{Timestamp when the bulk report was last updated in ISO-8601 format.}
#'   \item{`fileSize`}{Size of the bulk report output file in bytes.}
#' }
#'
#' @examples
#' \dontrun{
#' library(gfwr)
#'
#' # Retrieve the 10 most recent bulk reports
#' recent_reports <- gfw_get_all_bulk_reports(
#'   limit = 10,
#'   sort = "-createdAt",
#'   print_request = TRUE
#' )
#'
#' # List only reports that have successfully completed
#' completed_reports <- gfw_get_all_bulk_reports(
#'   status = "done"
#' )
#' }
#'
#' @keywords internal
#' @noRd
gfw_get_all_bulk_reports <- function(limit = 99999L,
                                     offset = 0L,
                                     sort = "-createdAt",
                                     status = NULL,
                                     key = gfw_auth(),
                                     print_request = FALSE) {
  ## Validate limit -----------------------------------------------------------
  if (!rlang::is_integerish(limit, n = 1, finite = TRUE) || limit < 0) {
    rlang::abort("`limit` must be a non-negative integer value.")
  }
  limit <- as.integer(limit)

  ## Validate offset ----------------------------------------------------------
  if (!rlang::is_integerish(offset, n = 1, finite = TRUE) || offset < 0) {
    rlang::abort("`offset` must be a non-negative integer value.")
  }
  offset <- as.integer(offset)

  ## Validate sort ------------------------------------------------------------
  if (!is.null(sort)) {
    if (!rlang::is_string(sort) || !nzchar(sort)) {
      rlang::abort("`sort` must be a non-empty character string.")
    }
  }

  ## Validate status ----------------------------------------------------------
  if (!is.null(status)) {
    status <- rlang::arg_match0(
      arg = tolower(trimws(as.character(status))),
      values = c("pending", "processing", "done", "failed"),
      arg_nm = "status"
    )
  }

  ## Validate key -------------------------------------------------------------
  if (!rlang::is_string(key) || !nzchar(key)) {
    rlang::abort("No API token found. Set `GFW_TOKEN` or pass `key`.")
  }

  ## Build API request parameters ---------------------------------------------
  req_params <- list(
    limit = limit,
    offset = offset,
    sort = sort,
    status = status
  ) |> purrr::discard(is.null)

  ## Build API request --------------------------------------------------------
  req <- httr2::request(gfw_base_url()) |>
    httr2::req_url_path_append("bulk-reports") |>
    httr2::req_url_query(!!!req_params) |>
    httr2::req_auth_bearer_token(key) |>
    httr2::req_headers(
      `Content-Type` = "application/json"
    ) |>
    httr2::req_user_agent(gfw_user_agent()) |>
    httr2::req_error(body = \(x) parse_response_error(x)$formatted)

  if (print_request) {
    print(req)
  }

  # Perform request
  resp <- req |> httr2::req_perform()

  ## Build API response -------------------------------------------------------

  # Extract JSON response body
  resp_body <- httr2::resp_body_json(resp, check_type = TRUE, simplifyVector = FALSE)

  # Extract, filter and normalize response entries
  resp_entries <- purrr::pluck(resp_body, "entries", .default = list()) |>
    purrr::keep(\(entry) rlang::is_named(entry) && !rlang::is_empty(entry))

  # Return empty tibble for invalid or empty entries
  if (rlang::is_empty(resp_entries)) {
    return(tibble::tibble())
  }

  # Transform response entries to dataframe
  resp_df <- resp_entries |>
    purrr::map(\(entry) {
      entry |>
        purrr::map(\(val) if (is.null(val)) NA else if (is.list(val) || length(val) > 1) list(val) else val) |>
        tibble::as_tibble_row()
    }) |>
    purrr::list_rbind()

  return(resp_df)
}
